# Generated by Django 3.2.5 on 2021-07-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts_and_students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cohorts',
            new_name='Cohort',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
